/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem;

import java.util.*;

/**
 *
 * @author Lim Li Ping
 */
public class AdminMenu extends javax.swing.JFrame {

  private UserAdmin adminData = new UserAdmin(
    null,
    null,
    null,
    null,
    null,
    null
  );

  /**
   * Creates new form AdminMenu
   */
  public AdminMenu() {
    initComponents();
  }

  public void setCurrentAdminData(UserAdmin data) {
    this.adminData = data;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    Title = new javax.swing.JLabel();
    AdminLoginLab = new javax.swing.JLabel();
    RegisterAdminBtn = new javax.swing.JButton();
    ManageCarBtn = new javax.swing.JButton();
    ManageBookingBtn = new javax.swing.JButton();
    ManageInfoBtn = new javax.swing.JButton();
    ViewSalesBtn = new javax.swing.JButton();
    ExitBtn = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    Title.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
    Title.setForeground(new java.awt.Color(0, 51, 153));
    Title.setText("Welcome to Car Rental System");

    AdminLoginLab.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
    AdminLoginLab.setForeground(new java.awt.Color(0, 51, 204));
    AdminLoginLab.setText("Admin Menu");

    RegisterAdminBtn.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
    RegisterAdminBtn.setForeground(new java.awt.Color(0, 102, 204));
    RegisterAdminBtn.setText("Register Admin Account");
    RegisterAdminBtn.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          RegisterAdminBtnActionPerformed(evt);
        }
      }
    );

    ManageCarBtn.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
    ManageCarBtn.setForeground(new java.awt.Color(0, 102, 204));
    ManageCarBtn.setText("Manage Car");
    ManageCarBtn.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          ManageCarBtnActionPerformed(evt);
        }
      }
    );

    ManageBookingBtn.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
    ManageBookingBtn.setForeground(new java.awt.Color(0, 102, 204));
    ManageBookingBtn.setText("Manage Customer's Booking");
    ManageBookingBtn.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          ManageBookingBtnActionPerformed(evt);
        }
      }
    );

    ManageInfoBtn.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
    ManageInfoBtn.setForeground(new java.awt.Color(0, 102, 204));
    ManageInfoBtn.setText("Manage Personal Information");
    ManageInfoBtn.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          ManageInfoBtnActionPerformed(evt);
        }
      }
    );

    ViewSalesBtn.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
    ViewSalesBtn.setForeground(new java.awt.Color(0, 102, 204));
    ViewSalesBtn.setText("View Sales Report");
    ViewSalesBtn.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          ViewSalesBtnActionPerformed(evt);
        }
      }
    );

    ExitBtn.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
    ExitBtn.setForeground(new java.awt.Color(0, 102, 204));
    ExitBtn.setText("Logout");
    ExitBtn.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          ExitBtnActionPerformed(evt);
        }
      }
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(161, 161, 161)
            .addComponent(AdminLoginLab)
            .addGap(0, 0, Short.MAX_VALUE)
        )
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          layout
            .createSequentialGroup()
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
            .addGroup(
              layout
                .createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING,
                  false
                )
                .addComponent(
                  ManageInfoBtn,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  275,
                  Short.MAX_VALUE
                )
                .addComponent(
                  ManageBookingBtn,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  RegisterAdminBtn,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  ViewSalesBtn,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  ManageCarBtn,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
            )
            .addGap(100, 100, 100)
        )
        .addGroup(
          layout
            .createSequentialGroup()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(Title)
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                      ExitBtn,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      93,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
            )
            .addContainerGap(57, Short.MAX_VALUE)
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(ExitBtn)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Title)
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addComponent(AdminLoginLab)
            .addGap(18, 18, 18)
            .addComponent(ManageCarBtn)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(ViewSalesBtn)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(RegisterAdminBtn)
            .addGap(7, 7, 7)
            .addComponent(ManageBookingBtn)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(ManageInfoBtn)
            .addContainerGap(19, Short.MAX_VALUE)
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void RegisterAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO register account
    //
    RegisterAdmin registerMenu = new RegisterAdmin();
    registerMenu.setCurrentAdminData(adminData);
    registerMenu.setVisible(true);
    dispose();
  }

  private void ManageCarBtnActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    ManageCar manageCarMenu = new ManageCar();
    manageCarMenu.setCurrentAdminData(adminData);
    manageCarMenu.setVisible(true);
    dispose();
  }

  private void ManageBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO manage booking
    ManageBooking manageBookMenu = new ManageBooking();
    manageBookMenu.setCurrentAdminData(adminData);
    manageBookMenu.setVisible(true);
    dispose();
  }

  private void ManageInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO manage personal info
    ManageAccountAdmin adminAcc = new ManageAccountAdmin();
    adminAcc.setCurrentAdminData(adminData);
    adminAcc.setTextfieldData();
    adminAcc.setVisible(true);
    dispose();
  }

  private void ViewSalesBtnActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO sales report
    SalesReport sales = new SalesReport();
    sales.setCurrentAdminData(adminData);
    sales.setVisible(true);
    dispose();
  }

  private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_ExitBtnActionPerformed
    //Call the exit system function
    exitSystem exit = new exitSystem();
    if (!exit.exitsystem(adminData)) return;
    LoginMenu menu = new LoginMenu();
    menu.setVisible(true);
    dispose();
  } //GEN-LAST:event_ExitBtnActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger
        .getLogger(AdminMenu.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger
        .getLogger(AdminMenu.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger
        .getLogger(AdminMenu.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger
        .getLogger(AdminMenu.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {
        public void run() {
          new AdminMenu().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel AdminLoginLab;
  private javax.swing.JButton ExitBtn;
  private javax.swing.JButton ManageBookingBtn;
  private javax.swing.JButton ManageCarBtn;
  private javax.swing.JButton ManageInfoBtn;
  private javax.swing.JButton RegisterAdminBtn;
  private javax.swing.JLabel Title;
  private javax.swing.JButton ViewSalesBtn;
  // End of variables declaration//GEN-END:variables
}
