/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem;

/**
 *
 * @author Lim Li Ping
 */
public class BookCar extends javax.swing.JFrame {

  /**
   * Creates new form BookCar
   */
  public BookCar() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    CustDetails = new javax.swing.JPanel();
    Passport = new javax.swing.JLabel();
    IC = new javax.swing.JTextField();
    Contact = new javax.swing.JLabel();
    CustName = new javax.swing.JTextField();
    Name = new javax.swing.JLabel();
    PhNum = new javax.swing.JTextField();
    Mail = new javax.swing.JLabel();
    Email = new javax.swing.JTextField();
    CustDetailsLab = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    Title = new javax.swing.JLabel();
    MenuBut = new javax.swing.JButton();
    search = new javax.swing.JButton();
    BookBtn = new javax.swing.JButton();
    clearBut = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    RoomDetails = new javax.swing.JPanel();
    RoomTypeLab = new javax.swing.JLabel();
    Room = new javax.swing.JLabel();
    Day = new javax.swing.JLabel();
    RoomDetailsLab = new javax.swing.JLabel();
    DayStay = new javax.swing.JTextField();
    CarNoPlate = new javax.swing.JTextField();
    RoomID = new javax.swing.JComboBox<>();
    BookingLab = new javax.swing.JLabel();
    BookingLab2 = new javax.swing.JLabel();
    EndDate = new javax.swing.JTextField();
    EndDate1 = new javax.swing.JTextField();
    Room1 = new javax.swing.JLabel();
    EndDate2 = new javax.swing.JTextField();
    Room2 = new javax.swing.JLabel();
    RoomID1 = new javax.swing.JComboBox<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    CustDetails.setBorder(
      javax.swing.BorderFactory.createLineBorder(
        new java.awt.Color(210, 204, 228),
        4
      )
    );

    Passport.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    Passport.setForeground(new java.awt.Color(140, 174, 238));
    Passport.setText("IC/Passport:");

    Contact.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    Contact.setForeground(new java.awt.Color(140, 174, 238));
    Contact.setText("Phone Number:");

    Name.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    Name.setForeground(new java.awt.Color(140, 174, 238));
    Name.setText("Name:");

    Mail.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    Mail.setForeground(new java.awt.Color(140, 174, 238));
    Mail.setText("Email:");

    Email.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          EmailActionPerformed(evt);
        }
      }
    );

    CustDetailsLab.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
    CustDetailsLab.setForeground(new java.awt.Color(66, 129, 244));
    CustDetailsLab.setText("Customer Details");

    jLabel1.setText("** Enter IC to search records");

    javax.swing.GroupLayout CustDetailsLayout = new javax.swing.GroupLayout(
      CustDetails
    );
    CustDetails.setLayout(CustDetailsLayout);
    CustDetailsLayout.setHorizontalGroup(
      CustDetailsLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          CustDetailsLayout
            .createSequentialGroup()
            .addGroup(
              CustDetailsLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  CustDetailsLayout
                    .createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(
                      CustDetailsLayout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.TRAILING
                        )
                        .addComponent(Passport)
                        .addComponent(Name)
                        .addComponent(Contact)
                        .addComponent(
                          Mail,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          40,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                    .addGap(18, 18, 18)
                    .addGroup(
                      CustDetailsLayout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING,
                          false
                        )
                        .addComponent(
                          Email,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          209,
                          Short.MAX_VALUE
                        )
                        .addComponent(
                          PhNum,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          209,
                          Short.MAX_VALUE
                        )
                        .addComponent(CustDetailsLab)
                        .addComponent(
                          IC,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          209,
                          Short.MAX_VALUE
                        )
                        .addComponent(
                          CustName,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          209,
                          Short.MAX_VALUE
                        )
                    )
                )
                .addGroup(
                  CustDetailsLayout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                )
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );
    CustDetailsLayout.setVerticalGroup(
      CustDetailsLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          CustDetailsLayout
            .createSequentialGroup()
            .addGap(6, 6, 6)
            .addComponent(CustDetailsLab)
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addGroup(
              CustDetailsLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Passport)
                .addComponent(
                  IC,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  22,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addGroup(
              CustDetailsLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  CustName,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(Name)
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addGroup(
              CustDetailsLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  PhNum,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(Contact)
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addGroup(
              CustDetailsLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  Email,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(Mail)
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
            .addComponent(jLabel1)
            .addContainerGap()
        )
    );

    Title.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
    Title.setForeground(new java.awt.Color(0, 51, 153));
    Title.setText("Welcome to Car Rental System");

    MenuBut.setBackground(new java.awt.Color(153, 204, 255));
    MenuBut.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    MenuBut.setForeground(new java.awt.Color(0, 102, 255));
    MenuBut.setText("Main Menu");
    MenuBut.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          MenuButActionPerformed(evt);
        }
      }
    );

    search.setBackground(new java.awt.Color(153, 204, 255));
    search.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
    search.setForeground(new java.awt.Color(0, 102, 255));
    search.setText("Search");
    search.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          searchActionPerformed(evt);
        }
      }
    );

    BookBtn.setBackground(new java.awt.Color(255, 255, 255));
    BookBtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
    BookBtn.setForeground(new java.awt.Color(0, 102, 255));
    BookBtn.setText("Book Car");
    BookBtn.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          BookBtnActionPerformed(evt);
        }
      }
    );

    clearBut.setBackground(new java.awt.Color(153, 204, 255));
    clearBut.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
    clearBut.setForeground(new java.awt.Color(0, 102, 255));
    clearBut.setText("Clear");
    clearBut.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          clearButActionPerformed(evt);
        }
      }
    );

    jTable1.setFont(new java.awt.Font("STZhongsong", 0, 14)); // NOI18N
    jTable1.setModel(
      new javax.swing.table.DefaultTableModel(
        new Object[][] {
          { null, null, null, null, null, null, null },
          { null, null, null, null, null, null, null },
          { null, null, null, null, null, null, null },
          { null, null, null, null, null, null, null },
        },
        new String[] {
          "Car No Plate",
          "Brand",
          "Model",
          "Year",
          "Type of Fuel",
          "Price",
          "Status",
        }
      ) {
        Class[] types = new Class[] {
          java.lang.String.class,
          java.lang.String.class,
          java.lang.String.class,
          java.lang.Integer.class,
          java.lang.String.class,
          java.lang.Double.class,
          java.lang.String.class,
        };

        public Class getColumnClass(int columnIndex) {
          return types[columnIndex];
        }
      }
    );
    jScrollPane1.setViewportView(jTable1);

    RoomDetails.setBorder(
      javax.swing.BorderFactory.createLineBorder(
        new java.awt.Color(210, 204, 228),
        4
      )
    );

    RoomTypeLab.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    RoomTypeLab.setForeground(new java.awt.Color(140, 174, 238));
    RoomTypeLab.setText("Year:");

    Room.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    Room.setForeground(new java.awt.Color(140, 174, 238));
    Room.setText("Type of Fuel:");

    Day.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    Day.setForeground(new java.awt.Color(140, 174, 238));
    Day.setText("Brand:");

    RoomDetailsLab.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
    RoomDetailsLab.setForeground(new java.awt.Color(66, 129, 244));
    RoomDetailsLab.setText("Car Details");

    DayStay.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          DayStayActionPerformed(evt);
        }
      }
    );

    CarNoPlate.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          CarNoPlateActionPerformed(evt);
        }
      }
    );

    RoomID.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
    RoomID.setModel(
      new javax.swing.DefaultComboBoxModel<>(
        new String[] { "Petron", "Diesel" }
      )
    );
    RoomID.addContainerListener(
      new java.awt.event.ContainerAdapter() {
        public void componentAdded(java.awt.event.ContainerEvent evt) {
          RoomIDComponentAdded(evt);
        }
      }
    );
    RoomID.addItemListener(
      new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
          RoomIDItemStateChanged(evt);
        }
      }
    );
    RoomID.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          RoomIDActionPerformed(evt);
        }
      }
    );

    BookingLab.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    BookingLab.setForeground(new java.awt.Color(140, 174, 238));
    BookingLab.setText("Car No. Plate:");

    BookingLab2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    BookingLab2.setForeground(new java.awt.Color(140, 174, 238));
    BookingLab2.setText("Model:");

    EndDate.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          EndDateActionPerformed(evt);
        }
      }
    );

    EndDate1.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          EndDate1ActionPerformed(evt);
        }
      }
    );

    Room1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    Room1.setForeground(new java.awt.Color(140, 174, 238));
    Room1.setText("Price:");

    EndDate2.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          EndDate2ActionPerformed(evt);
        }
      }
    );

    Room2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
    Room2.setForeground(new java.awt.Color(140, 174, 238));
    Room2.setText("Status:");

    RoomID1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
    RoomID1.setModel(
      new javax.swing.DefaultComboBoxModel<>(
        new String[] { "Available", "Not Available" }
      )
    );
    RoomID1.addContainerListener(
      new java.awt.event.ContainerAdapter() {
        public void componentAdded(java.awt.event.ContainerEvent evt) {
          RoomID1ComponentAdded(evt);
        }
      }
    );
    RoomID1.addItemListener(
      new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
          RoomID1ItemStateChanged(evt);
        }
      }
    );
    RoomID1.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          RoomID1ActionPerformed(evt);
        }
      }
    );

    javax.swing.GroupLayout RoomDetailsLayout = new javax.swing.GroupLayout(
      RoomDetails
    );
    RoomDetails.setLayout(RoomDetailsLayout);
    RoomDetailsLayout.setHorizontalGroup(
      RoomDetailsLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          RoomDetailsLayout
            .createSequentialGroup()
            .addGroup(
              RoomDetailsLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  RoomDetailsLayout
                    .createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addComponent(RoomDetailsLab)
                )
                .addGroup(
                  RoomDetailsLayout
                    .createSequentialGroup()
                    .addGroup(
                      RoomDetailsLayout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          RoomDetailsLayout
                            .createSequentialGroup()
                            .addGroup(
                              RoomDetailsLayout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.LEADING,
                                  false
                                )
                                .addGroup(
                                  RoomDetailsLayout
                                    .createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(Room)
                                    .addGap(18, 18, 18)
                                    .addComponent(
                                      RoomID,
                                      0,
                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                      Short.MAX_VALUE
                                    )
                                )
                                .addGroup(
                                  RoomDetailsLayout
                                    .createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(BookingLab)
                                    .addGap(16, 16, 16)
                                    .addComponent(
                                      CarNoPlate,
                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                      110,
                                      javax.swing.GroupLayout.PREFERRED_SIZE
                                    )
                                )
                            )
                            .addGap(0, 0, Short.MAX_VALUE)
                        )
                        .addGroup(
                          javax.swing.GroupLayout.Alignment.TRAILING,
                          RoomDetailsLayout
                            .createSequentialGroup()
                            .addContainerGap(
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              Short.MAX_VALUE
                            )
                            .addGroup(
                              RoomDetailsLayout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.LEADING
                                )
                                .addGroup(
                                  javax.swing.GroupLayout.Alignment.TRAILING,
                                  RoomDetailsLayout
                                    .createSequentialGroup()
                                    .addComponent(Day)
                                    .addGap(18, 18, 18)
                                    .addComponent(
                                      DayStay,
                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                      110,
                                      javax.swing.GroupLayout.PREFERRED_SIZE
                                    )
                                )
                                .addGroup(
                                  javax.swing.GroupLayout.Alignment.TRAILING,
                                  RoomDetailsLayout
                                    .createSequentialGroup()
                                    .addComponent(BookingLab2)
                                    .addGap(18, 18, 18)
                                    .addComponent(
                                      EndDate,
                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                      110,
                                      javax.swing.GroupLayout.PREFERRED_SIZE
                                    )
                                )
                                .addGroup(
                                  javax.swing.GroupLayout.Alignment.TRAILING,
                                  RoomDetailsLayout
                                    .createSequentialGroup()
                                    .addComponent(RoomTypeLab)
                                    .addGap(18, 18, 18)
                                    .addComponent(
                                      EndDate1,
                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                      110,
                                      javax.swing.GroupLayout.PREFERRED_SIZE
                                    )
                                )
                            )
                        )
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                      31,
                      Short.MAX_VALUE
                    )
                    .addGroup(
                      RoomDetailsLayout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING,
                          false
                        )
                        .addGroup(
                          RoomDetailsLayout
                            .createSequentialGroup()
                            .addComponent(Room1)
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
                            )
                            .addComponent(
                              EndDate2,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              110,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                        .addGroup(
                          RoomDetailsLayout
                            .createSequentialGroup()
                            .addComponent(Room2)
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              Short.MAX_VALUE
                            )
                            .addComponent(
                              RoomID1,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              108,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                    )
                )
            )
            .addContainerGap()
        )
    );
    RoomDetailsLayout.setVerticalGroup(
      RoomDetailsLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          RoomDetailsLayout
            .createSequentialGroup()
            .addComponent(
              RoomDetailsLab,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              34,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              RoomDetailsLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  BookingLab,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  21,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  CarNoPlate,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  EndDate2,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(Room1)
            )
            .addGap(18, 18, 18)
            .addGroup(
              RoomDetailsLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  DayStay,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  20,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(Room2)
                .addComponent(
                  RoomID1,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  23,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(Day)
            )
            .addGap(18, 18, 18)
            .addGroup(
              RoomDetailsLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  EndDate,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  BookingLab2,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  21,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(18, 18, 18)
            .addGroup(
              RoomDetailsLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(RoomTypeLab)
                .addComponent(
                  EndDate1,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(18, 18, 18)
            .addGroup(
              RoomDetailsLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Room)
                .addComponent(
                  RoomID,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  23,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addComponent(MenuBut)
                    .addGap(115, 115, 115)
                    .addComponent(Title)
                    .addGap(0, 410, Short.MAX_VALUE)
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  layout
                    .createSequentialGroup()
                    .addComponent(
                      RoomDetails,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                    .addComponent(
                      CustDetails,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addGap(34, 34, 34)
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING,
                          false
                        )
                        .addComponent(
                          search,
                          javax.swing.GroupLayout.Alignment.TRAILING,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          Short.MAX_VALUE
                        )
                        .addComponent(
                          BookBtn,
                          javax.swing.GroupLayout.Alignment.TRAILING,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          188,
                          Short.MAX_VALUE
                        )
                        .addComponent(
                          clearBut,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          Short.MAX_VALUE
                        )
                    )
                )
                .addComponent(jScrollPane1)
            )
            .addContainerGap()
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addComponent(MenuBut)
                    .addGap(24, 24, 24)
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  layout
                    .createSequentialGroup()
                    .addComponent(Title)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
                    )
                )
            )
            .addGroup(
              layout
                .createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING,
                  false
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addComponent(BookBtn)
                    .addGap(18, 18, 18)
                    .addComponent(search)
                    .addGap(18, 18, 18)
                    .addComponent(clearBut)
                )
                .addComponent(
                  RoomDetails,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  CustDetails,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
            )
            .addGap(18, 18, 18)
            .addComponent(
              jScrollPane1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              228,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addContainerGap(55, Short.MAX_VALUE)
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void EmailActionPerformed(java.awt.event.ActionEvent evt) {} //GEN-FIRST:event_EmailActionPerformed //GEN-LAST:event_EmailActionPerformed

  private void MenuButActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_MenuButActionPerformed
    //Direct to main menu
    AdminMenu menu = new AdminMenu();
    menu.setVisible(true);
    dispose();
  } //GEN-LAST:event_MenuButActionPerformed

  private void searchActionPerformed(java.awt.event.ActionEvent evt) {} //GEN-FIRST:event_searchActionPerformed //GEN-LAST:event_searchActionPerformed

  private void BookBtnActionPerformed(java.awt.event.ActionEvent evt) {} //GEN-FIRST:event_BookBtnActionPerformed //GEN-LAST:event_BookBtnActionPerformed

  private void clearButActionPerformed(java.awt.event.ActionEvent evt) {} //GEN-FIRST:event_clearButActionPerformed //GEN-LAST:event_clearButActionPerformed

  private void DayStayActionPerformed(java.awt.event.ActionEvent evt) {} //GEN-FIRST:event_DayStayActionPerformed //GEN-LAST:event_DayStayActionPerformed

  private void CarNoPlateActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_CarNoPlateActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_CarNoPlateActionPerformed

  private void RoomIDComponentAdded(java.awt.event.ContainerEvent evt) {} //GEN-FIRST:event_RoomIDComponentAdded //GEN-LAST:event_RoomIDComponentAdded

  private void RoomIDItemStateChanged(java.awt.event.ItemEvent evt) {} //GEN-FIRST:event_RoomIDItemStateChanged //GEN-LAST:event_RoomIDItemStateChanged

  private void RoomIDActionPerformed(java.awt.event.ActionEvent evt) {} //GEN-FIRST:event_RoomIDActionPerformed //GEN-LAST:event_RoomIDActionPerformed

  private void EndDateActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_EndDateActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_EndDateActionPerformed

  private void EndDate1ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_EndDate1ActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_EndDate1ActionPerformed

  private void EndDate2ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_EndDate2ActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_EndDate2ActionPerformed

  private void RoomID1ComponentAdded(java.awt.event.ContainerEvent evt) { //GEN-FIRST:event_RoomID1ComponentAdded
    // TODO add your handling code here:
  } //GEN-LAST:event_RoomID1ComponentAdded

  private void RoomID1ItemStateChanged(java.awt.event.ItemEvent evt) { //GEN-FIRST:event_RoomID1ItemStateChanged
    // TODO add your handling code here:
  } //GEN-LAST:event_RoomID1ItemStateChanged

  private void RoomID1ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_RoomID1ActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_RoomID1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger
        .getLogger(BookCar.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger
        .getLogger(BookCar.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger
        .getLogger(BookCar.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger
        .getLogger(BookCar.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {
        public void run() {
          new BookCar().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton BookBtn;
  private javax.swing.JLabel BookingLab;
  private javax.swing.JLabel BookingLab2;
  private javax.swing.JTextField CarNoPlate;
  private javax.swing.JLabel Contact;
  private javax.swing.JPanel CustDetails;
  private javax.swing.JLabel CustDetailsLab;
  private javax.swing.JTextField CustName;
  private javax.swing.JLabel Day;
  private javax.swing.JTextField DayStay;
  private javax.swing.JTextField Email;
  private javax.swing.JTextField EndDate;
  private javax.swing.JTextField EndDate1;
  private javax.swing.JTextField EndDate2;
  private javax.swing.JTextField IC;
  private javax.swing.JLabel Mail;
  private javax.swing.JButton MenuBut;
  private javax.swing.JLabel Name;
  private javax.swing.JLabel Passport;
  private javax.swing.JTextField PhNum;
  private javax.swing.JLabel Room;
  private javax.swing.JLabel Room1;
  private javax.swing.JLabel Room2;
  private javax.swing.JPanel RoomDetails;
  private javax.swing.JLabel RoomDetailsLab;
  private javax.swing.JComboBox<String> RoomID;
  private javax.swing.JComboBox<String> RoomID1;
  private javax.swing.JLabel RoomTypeLab;
  private javax.swing.JLabel Title;
  private javax.swing.JButton clearBut;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private javax.swing.JButton search;
  // End of variables declaration//GEN-END:variables
}
