/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem;

import java.util.*;

/**
 *
 * @author Lim Li Ping
 */
public class MemberMenu extends javax.swing.JFrame {

  private UserCustomer customerData = new UserCustomer(
    null,
    null,
    null,
    null,
    null
  );

  /**
   * Creates new form MemberMenu
   */
  public MemberMenu() {
    initComponents();
  }

  public void setCurrentCustomerData(UserCustomer data) {
    this.customerData = data;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    AdminLoginLab = new javax.swing.JLabel();
    BookCarBtn = new javax.swing.JButton();
    ManageInfoBtn = new javax.swing.JButton();
    ViewBookingBtn = new javax.swing.JButton();
    ExitBtn = new javax.swing.JButton();
    Title = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    AdminLoginLab.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
    AdminLoginLab.setForeground(new java.awt.Color(0, 51, 204));
    AdminLoginLab.setText("Member Menu");

    BookCarBtn.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
    BookCarBtn.setForeground(new java.awt.Color(0, 102, 204));
    BookCarBtn.setText("Book Car");
    BookCarBtn.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          BookCarBtnActionPerformed(evt);
        }
      }
    );

    ManageInfoBtn.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
    ManageInfoBtn.setForeground(new java.awt.Color(0, 102, 204));
    ManageInfoBtn.setText("Manage Personal Information");
    ManageInfoBtn.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          ManageInfoBtnActionPerformed(evt);
        }
      }
    );

    ViewBookingBtn.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
    ViewBookingBtn.setForeground(new java.awt.Color(0, 102, 204));
    ViewBookingBtn.setText("View Booking History");
    ViewBookingBtn.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          ViewBookingBtnActionPerformed(evt);
        }
      }
    );

    ExitBtn.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
    ExitBtn.setForeground(new java.awt.Color(0, 102, 204));
    ExitBtn.setText("Logout");
    ExitBtn.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          ExitBtnActionPerformed(evt);
        }
      }
    );

    Title.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
    Title.setForeground(new java.awt.Color(0, 51, 153));
    Title.setText("Welcome to Car Rental System");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ExitBtn)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(Title)
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(206, 206, 206)
                    .addComponent(BookCarBtn)
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(155, 155, 155)
                    .addComponent(ViewBookingBtn)
                )
            )
            .addContainerGap(42, Short.MAX_VALUE)
        )
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          layout
            .createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  layout
                    .createSequentialGroup()
                    .addComponent(AdminLoginLab)
                    .addGap(179, 179, 179)
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  layout
                    .createSequentialGroup()
                    .addComponent(
                      ManageInfoBtn,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      275,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addGap(117, 117, 117)
                )
            )
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ExitBtn)
                .addComponent(Title)
            )
            .addGap(1, 1, 1)
            .addComponent(AdminLoginLab)
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addComponent(BookCarBtn)
            .addGap(18, 18, 18)
            .addComponent(ViewBookingBtn)
            .addGap(18, 18, 18)
            .addComponent(ManageInfoBtn)
            .addContainerGap(21, Short.MAX_VALUE)
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void BookCarBtnActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_BookCarBtnActionPerformed
    BookCar bookCarMenu = new BookCar();
    bookCarMenu.setCurrentCustomerData(customerData);
    bookCarMenu.setVisible(true);
    dispose();
  } //GEN-LAST:event_BookCarBtnActionPerformed

  private void ManageInfoBtnActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_ManageInfoBtnActionPerformed
    ManageAccountMember memberAcc = new ManageAccountMember();
    memberAcc.setCurrentCustomerData(customerData);
    memberAcc.setTextfieldData();
    memberAcc.setVisible(true);
    dispose();
  } //GEN-LAST:event_ManageInfoBtnActionPerformed

  private void ViewBookingBtnActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_ViewBookingBtnActionPerformed
    BookingHistory booking = new BookingHistory();
    booking.setCurrentCustomerData(customerData);
    booking.setVisible(true);
    dispose();
  } //GEN-LAST:event_ViewBookingBtnActionPerformed

  private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_ExitBtnActionPerformed
    //Call the exit system function
    exitSystem exit = new exitSystem();
    exit.exitsystem(customerData);
  } //GEN-LAST:event_ExitBtnActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger
        .getLogger(MemberMenu.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger
        .getLogger(MemberMenu.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger
        .getLogger(MemberMenu.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger
        .getLogger(MemberMenu.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {
        public void run() {
          new MemberMenu().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel AdminLoginLab;
  private javax.swing.JButton BookCarBtn;
  private javax.swing.JButton ExitBtn;
  private javax.swing.JButton ManageInfoBtn;
  private javax.swing.JLabel Title;
  private javax.swing.JButton ViewBookingBtn;
  // End of variables declaration//GEN-END:variables

}
